name: Deploy to app01
on:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: lineageos-infra/app01-deploy@main
        with:
          api_key: ${{ secrets.APP01_API_KEY }}
          app: updater_backend
  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs:
      - deploy
    if: ${{ always() }}
    steps:
      - uses: nobrayner/discord-webhook@v1
        with:
          github-token: ${{ secrets.github_token }}
          discord-webhook: ${{ secrets.DISCORD_WEBHOOK }}
